version: "3.9"
services:
  ts-algo-workshop:
    environment:
      GH_TOKEN: ${GH_TOKEN}
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: volume
        source: vscode-server-extensions
        target: /home/node/.vscode-server/extensions
      - type: volume
        source: vscode-server-insiders-extensions
        target: /home/node/.vscode-server-insiders/extensions

volumes:
  vscode-server-extensions:
    name: ts-algo-workshop-vscode-server-extensions
  vscode-server-insiders-extensions:
    name: ts-algo-workshop-vscode-server-insiders-extensions
